name: Build LaTeX document


on:
  push:
  pull_request:
    types:
      - closed
    branches:
      - master


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile notes
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: notes/schur_complement

      - name: Update compiled PDFs in git repository
        if: github.event.pull_request.merged == true || github.event_name == 'push'
        run: |
          git config --global core.autocrlf false
          git config --global user.name 'CI PDF compiler'
          git config --global user.email '<>'
          git add notes/schur_complement/main.pdf

          git commit -m "Update compiled PDFs"
          git push
